name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: xhprof
        coverage: none
    - name: Install dependencies
      run: |
        if [ "${{ matrix.php-version }}" == "8.1" ]; then
          rm -f composer.lock
        fi
        composer install --no-progress
        composer update --with-all-dependencies
        if [ "${{ matrix.php-version }}" == "8.1" ]; then
          composer require --dev --with-all-dependencies "rector/rector":">=1.0.2"
        fi
    - name: Run tests
      run: composer tests
